version: '3'
services:
  
  api:
    build: ./src/api
    tty: true
    volumes: 
      - ./src/api:/go/src/api
    ports:
      - "3000:3000"
    links:
      - mysql

  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      YZ: ${TZ}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./mysql:/var/www/mysql